// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pub.proto

public final class Pub {
  private Pub() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Publication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string company = 1;</code>
     * @return Whether the company field is set.
     */
    boolean hasCompany();
    /**
     * <code>required string company = 1;</code>
     * @return The company.
     */
    java.lang.String getCompany();
    /**
     * <code>required string company = 1;</code>
     * @return The bytes for company.
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>required double value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required double value = 2;</code>
     * @return The value.
     */
    double getValue();

    /**
     * <code>required double drop = 3;</code>
     * @return Whether the drop field is set.
     */
    boolean hasDrop();
    /**
     * <code>required double drop = 3;</code>
     * @return The drop.
     */
    double getDrop();

    /**
     * <code>required double variation = 4;</code>
     * @return Whether the variation field is set.
     */
    boolean hasVariation();
    /**
     * <code>required double variation = 4;</code>
     * @return The variation.
     */
    double getVariation();

    /**
     * <code>required string date = 5;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>required string date = 5;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 5;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code Publication}
   */
  public static final class Publication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Publication)
      PublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Publication.newBuilder() to construct.
    private Publication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Publication() {
      company_ = "";
      date_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Publication();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Publication(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              company_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              drop_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              variation_ = input.readDouble();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              date_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pub.internal_static_Publication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pub.internal_static_Publication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pub.Publication.class, Pub.Publication.Builder.class);
    }

    private int bitField0_;
    public static final int COMPANY_FIELD_NUMBER = 1;
    private volatile java.lang.Object company_;
    /**
     * <code>required string company = 1;</code>
     * @return Whether the company field is set.
     */
    @java.lang.Override
    public boolean hasCompany() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string company = 1;</code>
     * @return The company.
     */
    @java.lang.Override
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          company_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string company = 1;</code>
     * @return The bytes for company.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>required double value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }

    public static final int DROP_FIELD_NUMBER = 3;
    private double drop_;
    /**
     * <code>required double drop = 3;</code>
     * @return Whether the drop field is set.
     */
    @java.lang.Override
    public boolean hasDrop() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double drop = 3;</code>
     * @return The drop.
     */
    @java.lang.Override
    public double getDrop() {
      return drop_;
    }

    public static final int VARIATION_FIELD_NUMBER = 4;
    private double variation_;
    /**
     * <code>required double variation = 4;</code>
     * @return Whether the variation field is set.
     */
    @java.lang.Override
    public boolean hasVariation() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required double variation = 4;</code>
     * @return The variation.
     */
    @java.lang.Override
    public double getVariation() {
      return variation_;
    }

    public static final int DATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object date_;
    /**
     * <code>required string date = 5;</code>
     * @return Whether the date field is set.
     */
    @java.lang.Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string date = 5;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 5;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCompany()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDrop()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVariation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, company_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, value_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, drop_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, variation_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, date_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, company_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, drop_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, variation_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, date_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Pub.Publication)) {
        return super.equals(obj);
      }
      Pub.Publication other = (Pub.Publication) obj;

      if (hasCompany() != other.hasCompany()) return false;
      if (hasCompany()) {
        if (!getCompany()
            .equals(other.getCompany())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (java.lang.Double.doubleToLongBits(getValue())
            != java.lang.Double.doubleToLongBits(
                other.getValue())) return false;
      }
      if (hasDrop() != other.hasDrop()) return false;
      if (hasDrop()) {
        if (java.lang.Double.doubleToLongBits(getDrop())
            != java.lang.Double.doubleToLongBits(
                other.getDrop())) return false;
      }
      if (hasVariation() != other.hasVariation()) return false;
      if (hasVariation()) {
        if (java.lang.Double.doubleToLongBits(getVariation())
            != java.lang.Double.doubleToLongBits(
                other.getVariation())) return false;
      }
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCompany()) {
        hash = (37 * hash) + COMPANY_FIELD_NUMBER;
        hash = (53 * hash) + getCompany().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getValue()));
      }
      if (hasDrop()) {
        hash = (37 * hash) + DROP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDrop()));
      }
      if (hasVariation()) {
        hash = (37 * hash) + VARIATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getVariation()));
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Pub.Publication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pub.Publication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pub.Publication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pub.Publication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pub.Publication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pub.Publication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pub.Publication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pub.Publication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pub.Publication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Pub.Publication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pub.Publication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pub.Publication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Pub.Publication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Publication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Publication)
        Pub.PublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pub.internal_static_Publication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pub.internal_static_Publication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pub.Publication.class, Pub.Publication.Builder.class);
      }

      // Construct using Pub.Publication.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        company_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        drop_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        variation_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Pub.internal_static_Publication_descriptor;
      }

      @java.lang.Override
      public Pub.Publication getDefaultInstanceForType() {
        return Pub.Publication.getDefaultInstance();
      }

      @java.lang.Override
      public Pub.Publication build() {
        Pub.Publication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Pub.Publication buildPartial() {
        Pub.Publication result = new Pub.Publication(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.company_ = company_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.drop_ = drop_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.variation_ = variation_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.date_ = date_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Pub.Publication) {
          return mergeFrom((Pub.Publication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Pub.Publication other) {
        if (other == Pub.Publication.getDefaultInstance()) return this;
        if (other.hasCompany()) {
          bitField0_ |= 0x00000001;
          company_ = other.company_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasDrop()) {
          setDrop(other.getDrop());
        }
        if (other.hasVariation()) {
          setVariation(other.getVariation());
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000010;
          date_ = other.date_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCompany()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        if (!hasDrop()) {
          return false;
        }
        if (!hasVariation()) {
          return false;
        }
        if (!hasDate()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Pub.Publication parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Pub.Publication) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object company_ = "";
      /**
       * <code>required string company = 1;</code>
       * @return Whether the company field is set.
       */
      public boolean hasCompany() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string company = 1;</code>
       * @return The company.
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            company_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string company = 1;</code>
       * @return The bytes for company.
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string company = 1;</code>
       * @param value The company to set.
       * @return This builder for chaining.
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string company = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompany() {
        bitField0_ = (bitField0_ & ~0x00000001);
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>required string company = 1;</code>
       * @param value The bytes for company to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        company_ = value;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>required double value = 2;</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public double getValue() {
        return value_;
      }
      /**
       * <code>required double value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }

      private double drop_ ;
      /**
       * <code>required double drop = 3;</code>
       * @return Whether the drop field is set.
       */
      @java.lang.Override
      public boolean hasDrop() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double drop = 3;</code>
       * @return The drop.
       */
      @java.lang.Override
      public double getDrop() {
        return drop_;
      }
      /**
       * <code>required double drop = 3;</code>
       * @param value The drop to set.
       * @return This builder for chaining.
       */
      public Builder setDrop(double value) {
        bitField0_ |= 0x00000004;
        drop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double drop = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDrop() {
        bitField0_ = (bitField0_ & ~0x00000004);
        drop_ = 0D;
        onChanged();
        return this;
      }

      private double variation_ ;
      /**
       * <code>required double variation = 4;</code>
       * @return Whether the variation field is set.
       */
      @java.lang.Override
      public boolean hasVariation() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required double variation = 4;</code>
       * @return The variation.
       */
      @java.lang.Override
      public double getVariation() {
        return variation_;
      }
      /**
       * <code>required double variation = 4;</code>
       * @param value The variation to set.
       * @return This builder for chaining.
       */
      public Builder setVariation(double value) {
        bitField0_ |= 0x00000008;
        variation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double variation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVariation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        variation_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 5;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string date = 5;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 5;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 5;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 5;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        date_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Publication)
    }

    // @@protoc_insertion_point(class_scope:Publication)
    private static final Pub.Publication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pub.Publication();
    }

    public static Pub.Publication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Publication>
        PARSER = new com.google.protobuf.AbstractParser<Publication>() {
      @java.lang.Override
      public Publication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Publication(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Publication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Publication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Pub.Publication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Publication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Publication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007a.proto\"\\\n\013Publication\022\017\n\007company\030\001 \002(" +
      "\t\022\r\n\005value\030\002 \002(\001\022\014\n\004drop\030\003 \002(\001\022\021\n\tvariat" +
      "ion\030\004 \002(\001\022\014\n\004date\030\005 \002(\tB\005B\003Pub"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Publication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Publication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Publication_descriptor,
        new java.lang.String[] { "Company", "Value", "Drop", "Variation", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
